// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using SalesPortal.Client.CompensationPlan.GetCompensationPlan;
using SalesPortal.Client.CompensationPlan.ListCompensationPlans;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace SalesPortal.Client.CompensationPlan
{
    /// <summary>
    /// Builds and executes requests for operations under \CompensationPlan
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    public partial class CompensationPlanRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The GetCompensationPlan property</summary>
        public global::SalesPortal.Client.CompensationPlan.GetCompensationPlan.GetCompensationPlanRequestBuilder GetCompensationPlan
        {
            get => new global::SalesPortal.Client.CompensationPlan.GetCompensationPlan.GetCompensationPlanRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ListCompensationPlans property</summary>
        public global::SalesPortal.Client.CompensationPlan.ListCompensationPlans.ListCompensationPlansRequestBuilder ListCompensationPlans
        {
            get => new global::SalesPortal.Client.CompensationPlan.ListCompensationPlans.ListCompensationPlansRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SalesPortal.Client.CompensationPlan.CompensationPlanRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CompensationPlanRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/CompensationPlan", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SalesPortal.Client.CompensationPlan.CompensationPlanRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CompensationPlanRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/CompensationPlan", rawUrl)
        {
        }
    }
}
