// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using SalesPortal.Client.Person.CreatePerson;
using SalesPortal.Client.Person.GetPerson;
using SalesPortal.Client.Person.UpdatePerson;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace SalesPortal.Client.Person
{
    /// <summary>
    /// Builds and executes requests for operations under \Person
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.19.0")]
    public partial class PersonRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The CreatePerson property</summary>
        public global::SalesPortal.Client.Person.CreatePerson.CreatePersonRequestBuilder CreatePerson
        {
            get => new global::SalesPortal.Client.Person.CreatePerson.CreatePersonRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetPerson property</summary>
        public global::SalesPortal.Client.Person.GetPerson.GetPersonRequestBuilder GetPerson
        {
            get => new global::SalesPortal.Client.Person.GetPerson.GetPersonRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The UpdatePerson property</summary>
        public global::SalesPortal.Client.Person.UpdatePerson.UpdatePersonRequestBuilder UpdatePerson
        {
            get => new global::SalesPortal.Client.Person.UpdatePerson.UpdatePersonRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SalesPortal.Client.Person.PersonRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PersonRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Person", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SalesPortal.Client.Person.PersonRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PersonRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Person", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
