// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using SalesPortal.Client.Product.CreateProduct;
using SalesPortal.Client.Product.GetProduct;
using SalesPortal.Client.Product.ListProducts;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace SalesPortal.Client.Product
{
    /// <summary>
    /// Builds and executes requests for operations under \Product
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.19.0")]
    public partial class ProductRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The CreateProduct property</summary>
        public global::SalesPortal.Client.Product.CreateProduct.CreateProductRequestBuilder CreateProduct
        {
            get => new global::SalesPortal.Client.Product.CreateProduct.CreateProductRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetProduct property</summary>
        public global::SalesPortal.Client.Product.GetProduct.GetProductRequestBuilder GetProduct
        {
            get => new global::SalesPortal.Client.Product.GetProduct.GetProductRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ListProducts property</summary>
        public global::SalesPortal.Client.Product.ListProducts.ListProductsRequestBuilder ListProducts
        {
            get => new global::SalesPortal.Client.Product.ListProducts.ListProductsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SalesPortal.Client.Product.ProductRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProductRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Product", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SalesPortal.Client.Product.ProductRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProductRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Product", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
