// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using SalesPortal.Client.SalesGroup.CreateSalesGroup;
using SalesPortal.Client.SalesGroup.GetSalesGroup;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace SalesPortal.Client.SalesGroup
{
    /// <summary>
    /// Builds and executes requests for operations under \SalesGroup
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.19.0")]
    public partial class SalesGroupRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The CreateSalesGroup property</summary>
        public global::SalesPortal.Client.SalesGroup.CreateSalesGroup.CreateSalesGroupRequestBuilder CreateSalesGroup
        {
            get => new global::SalesPortal.Client.SalesGroup.CreateSalesGroup.CreateSalesGroupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetSalesGroup property</summary>
        public global::SalesPortal.Client.SalesGroup.GetSalesGroup.GetSalesGroupRequestBuilder GetSalesGroup
        {
            get => new global::SalesPortal.Client.SalesGroup.GetSalesGroup.GetSalesGroupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SalesPortal.Client.SalesGroup.SalesGroupRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SalesGroupRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/SalesGroup", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SalesPortal.Client.SalesGroup.SalesGroupRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SalesGroupRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/SalesGroup", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
