// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using SalesPortal.Client.CreditNote.GetCreditNote;
using SalesPortal.Client.CreditNote.ListCreditNote;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace SalesPortal.Client.CreditNote
{
    /// <summary>
    /// Builds and executes requests for operations under \CreditNote
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.19.0")]
    public partial class CreditNoteRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The GetCreditNote property</summary>
        public global::SalesPortal.Client.CreditNote.GetCreditNote.GetCreditNoteRequestBuilder GetCreditNote
        {
            get => new global::SalesPortal.Client.CreditNote.GetCreditNote.GetCreditNoteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ListCreditNote property</summary>
        public global::SalesPortal.Client.CreditNote.ListCreditNote.ListCreditNoteRequestBuilder ListCreditNote
        {
            get => new global::SalesPortal.Client.CreditNote.ListCreditNote.ListCreditNoteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SalesPortal.Client.CreditNote.CreditNoteRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CreditNoteRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/CreditNote", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SalesPortal.Client.CreditNote.CreditNoteRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CreditNoteRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/CreditNote", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
