// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using SalesPortal.Client.MonthlyReport.CalculateMonthlyReport;
using SalesPortal.Client.MonthlyReport.GetMonthlyReport;
using SalesPortal.Client.MonthlyReport.ListMonthlyReport;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace SalesPortal.Client.MonthlyReport
{
    /// <summary>
    /// Builds and executes requests for operations under \MonthlyReport
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.19.0")]
    public partial class MonthlyReportRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The CalculateMonthlyReport property</summary>
        public global::SalesPortal.Client.MonthlyReport.CalculateMonthlyReport.CalculateMonthlyReportRequestBuilder CalculateMonthlyReport
        {
            get => new global::SalesPortal.Client.MonthlyReport.CalculateMonthlyReport.CalculateMonthlyReportRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetMonthlyReport property</summary>
        public global::SalesPortal.Client.MonthlyReport.GetMonthlyReport.GetMonthlyReportRequestBuilder GetMonthlyReport
        {
            get => new global::SalesPortal.Client.MonthlyReport.GetMonthlyReport.GetMonthlyReportRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ListMonthlyReport property</summary>
        public global::SalesPortal.Client.MonthlyReport.ListMonthlyReport.ListMonthlyReportRequestBuilder ListMonthlyReport
        {
            get => new global::SalesPortal.Client.MonthlyReport.ListMonthlyReport.ListMonthlyReportRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SalesPortal.Client.MonthlyReport.MonthlyReportRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MonthlyReportRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/MonthlyReport", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SalesPortal.Client.MonthlyReport.MonthlyReportRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MonthlyReportRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/MonthlyReport", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
