// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SalesPortal.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.19.0")]
    #pragma warning disable CS1591
    public partial class AchievementDefinition : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The achievements property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::SalesPortal.Client.Models.Achievement>? Achievements { get; set; }
#nullable restore
#else
        public List<global::SalesPortal.Client.Models.Achievement> Achievements { get; set; }
#endif
        /// <summary>The commissionPool property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SalesPortal.Client.Models.CommissionPool? CommissionPool { get; set; }
#nullable restore
#else
        public global::SalesPortal.Client.Models.CommissionPool CommissionPool { get; set; }
#endif
        /// <summary>The commissionPoolId property</summary>
        public long? CommissionPoolId { get; set; }
        /// <summary>The compensationPlan property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SalesPortal.Client.Models.CompensationPlan? CompensationPlan { get; set; }
#nullable restore
#else
        public global::SalesPortal.Client.Models.CompensationPlan CompensationPlan { get; set; }
#endif
        /// <summary>The compensationPlanId property</summary>
        public long? CompensationPlanId { get; set; }
        /// <summary>The id property</summary>
        public long? Id { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The operatorType property</summary>
        public int? OperatorType { get; set; }
        /// <summary>The requiredCommission property</summary>
        public double? RequiredCommission { get; set; }
        /// <summary>The requiredCommissionPreviousMonths property</summary>
        public int? RequiredCommissionPreviousMonths { get; set; }
        /// <summary>The requiredTeamsize property</summary>
        public double? RequiredTeamsize { get; set; }
        /// <summary>The requiredTurnover property</summary>
        public double? RequiredTurnover { get; set; }
        /// <summary>The requiredTurnoverPreviousMonths property</summary>
        public int? RequiredTurnoverPreviousMonths { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SalesPortal.Client.Models.AchievementDefinition"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SalesPortal.Client.Models.AchievementDefinition CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::SalesPortal.Client.Models.AchievementDefinition();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "achievements", n => { Achievements = n.GetCollectionOfObjectValues<global::SalesPortal.Client.Models.Achievement>(global::SalesPortal.Client.Models.Achievement.CreateFromDiscriminatorValue)?.AsList(); } },
                { "commissionPool", n => { CommissionPool = n.GetObjectValue<global::SalesPortal.Client.Models.CommissionPool>(global::SalesPortal.Client.Models.CommissionPool.CreateFromDiscriminatorValue); } },
                { "commissionPoolId", n => { CommissionPoolId = n.GetLongValue(); } },
                { "compensationPlan", n => { CompensationPlan = n.GetObjectValue<global::SalesPortal.Client.Models.CompensationPlan>(global::SalesPortal.Client.Models.CompensationPlan.CreateFromDiscriminatorValue); } },
                { "compensationPlanId", n => { CompensationPlanId = n.GetLongValue(); } },
                { "id", n => { Id = n.GetLongValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "operatorType", n => { OperatorType = n.GetIntValue(); } },
                { "requiredCommission", n => { RequiredCommission = n.GetDoubleValue(); } },
                { "requiredCommissionPreviousMonths", n => { RequiredCommissionPreviousMonths = n.GetIntValue(); } },
                { "requiredTeamsize", n => { RequiredTeamsize = n.GetDoubleValue(); } },
                { "requiredTurnover", n => { RequiredTurnover = n.GetDoubleValue(); } },
                { "requiredTurnoverPreviousMonths", n => { RequiredTurnoverPreviousMonths = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::SalesPortal.Client.Models.Achievement>("achievements", Achievements);
            writer.WriteObjectValue<global::SalesPortal.Client.Models.CommissionPool>("commissionPool", CommissionPool);
            writer.WriteLongValue("commissionPoolId", CommissionPoolId);
            writer.WriteObjectValue<global::SalesPortal.Client.Models.CompensationPlan>("compensationPlan", CompensationPlan);
            writer.WriteLongValue("compensationPlanId", CompensationPlanId);
            writer.WriteLongValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("operatorType", OperatorType);
            writer.WriteDoubleValue("requiredCommission", RequiredCommission);
            writer.WriteIntValue("requiredCommissionPreviousMonths", RequiredCommissionPreviousMonths);
            writer.WriteDoubleValue("requiredTeamsize", RequiredTeamsize);
            writer.WriteDoubleValue("requiredTurnover", RequiredTurnover);
            writer.WriteIntValue("requiredTurnoverPreviousMonths", RequiredTurnoverPreviousMonths);
        }
    }
}
#pragma warning restore CS0618
