// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SalesPortal.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    #pragma warning disable CS1591
    public partial class Commission : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The commissionPool property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SalesPortal.Client.Models.CommissionPool? CommissionPool { get; set; }
#nullable restore
#else
        public global::SalesPortal.Client.Models.CommissionPool CommissionPool { get; set; }
#endif
        /// <summary>The commissionPoolId property</summary>
        public long? CommissionPoolId { get; set; }
        /// <summary>The creditNote property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SalesPortal.Client.Models.CreditNote? CreditNote { get; set; }
#nullable restore
#else
        public global::SalesPortal.Client.Models.CreditNote CreditNote { get; set; }
#endif
        /// <summary>The creditNoteId property</summary>
        public long? CreditNoteId { get; set; }
        /// <summary>The id property</summary>
        public long? Id { get; set; }
        /// <summary>The monthlyReport property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SalesPortal.Client.Models.MonthlyReport? MonthlyReport { get; set; }
#nullable restore
#else
        public global::SalesPortal.Client.Models.MonthlyReport MonthlyReport { get; set; }
#endif
        /// <summary>The monthlyReportId property</summary>
        public long? MonthlyReportId { get; set; }
        /// <summary>The node property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SalesPortal.Client.Models.Node? Node { get; set; }
#nullable restore
#else
        public global::SalesPortal.Client.Models.Node Node { get; set; }
#endif
        /// <summary>The nodeId property</summary>
        public long? NodeId { get; set; }
        /// <summary>The sale property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SalesPortal.Client.Models.Sale? Sale { get; set; }
#nullable restore
#else
        public global::SalesPortal.Client.Models.Sale Sale { get; set; }
#endif
        /// <summary>The saleId property</summary>
        public long? SaleId { get; set; }
        /// <summary>The share property</summary>
        public double? Share { get; set; }
        /// <summary>The value property</summary>
        public double? Value { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SalesPortal.Client.Models.Commission"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SalesPortal.Client.Models.Commission CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::SalesPortal.Client.Models.Commission();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "commissionPool", n => { CommissionPool = n.GetObjectValue<global::SalesPortal.Client.Models.CommissionPool>(global::SalesPortal.Client.Models.CommissionPool.CreateFromDiscriminatorValue); } },
                { "commissionPoolId", n => { CommissionPoolId = n.GetLongValue(); } },
                { "creditNote", n => { CreditNote = n.GetObjectValue<global::SalesPortal.Client.Models.CreditNote>(global::SalesPortal.Client.Models.CreditNote.CreateFromDiscriminatorValue); } },
                { "creditNoteId", n => { CreditNoteId = n.GetLongValue(); } },
                { "id", n => { Id = n.GetLongValue(); } },
                { "monthlyReport", n => { MonthlyReport = n.GetObjectValue<global::SalesPortal.Client.Models.MonthlyReport>(global::SalesPortal.Client.Models.MonthlyReport.CreateFromDiscriminatorValue); } },
                { "monthlyReportId", n => { MonthlyReportId = n.GetLongValue(); } },
                { "node", n => { Node = n.GetObjectValue<global::SalesPortal.Client.Models.Node>(global::SalesPortal.Client.Models.Node.CreateFromDiscriminatorValue); } },
                { "nodeId", n => { NodeId = n.GetLongValue(); } },
                { "sale", n => { Sale = n.GetObjectValue<global::SalesPortal.Client.Models.Sale>(global::SalesPortal.Client.Models.Sale.CreateFromDiscriminatorValue); } },
                { "saleId", n => { SaleId = n.GetLongValue(); } },
                { "share", n => { Share = n.GetDoubleValue(); } },
                { "value", n => { Value = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::SalesPortal.Client.Models.CommissionPool>("commissionPool", CommissionPool);
            writer.WriteLongValue("commissionPoolId", CommissionPoolId);
            writer.WriteObjectValue<global::SalesPortal.Client.Models.CreditNote>("creditNote", CreditNote);
            writer.WriteLongValue("creditNoteId", CreditNoteId);
            writer.WriteLongValue("id", Id);
            writer.WriteObjectValue<global::SalesPortal.Client.Models.MonthlyReport>("monthlyReport", MonthlyReport);
            writer.WriteLongValue("monthlyReportId", MonthlyReportId);
            writer.WriteObjectValue<global::SalesPortal.Client.Models.Node>("node", Node);
            writer.WriteLongValue("nodeId", NodeId);
            writer.WriteObjectValue<global::SalesPortal.Client.Models.Sale>("sale", Sale);
            writer.WriteLongValue("saleId", SaleId);
            writer.WriteDoubleValue("share", Share);
            writer.WriteDoubleValue("value", Value);
        }
    }
}
