// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SalesPortal.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    #pragma warning disable CS1591
    public partial class CommissionPool : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The achievementDefinitions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::SalesPortal.Client.Models.AchievementDefinition>? AchievementDefinitions { get; set; }
#nullable restore
#else
        public List<global::SalesPortal.Client.Models.AchievementDefinition> AchievementDefinitions { get; set; }
#endif
        /// <summary>The commissionPayouts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::SalesPortal.Client.Models.CommissionPoolPayout>? CommissionPayouts { get; set; }
#nullable restore
#else
        public List<global::SalesPortal.Client.Models.CommissionPoolPayout> CommissionPayouts { get; set; }
#endif
        /// <summary>The commissions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::SalesPortal.Client.Models.Commission>? Commissions { get; set; }
#nullable restore
#else
        public List<global::SalesPortal.Client.Models.Commission> Commissions { get; set; }
#endif
        /// <summary>The compensationPlan property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SalesPortal.Client.Models.CompensationPlan? CompensationPlan { get; set; }
#nullable restore
#else
        public global::SalesPortal.Client.Models.CompensationPlan CompensationPlan { get; set; }
#endif
        /// <summary>The compensationPlanId property</summary>
        public long? CompensationPlanId { get; set; }
        /// <summary>The id property</summary>
        public long? Id { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The share property</summary>
        public double? Share { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SalesPortal.Client.Models.CommissionPool"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SalesPortal.Client.Models.CommissionPool CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::SalesPortal.Client.Models.CommissionPool();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "achievementDefinitions", n => { AchievementDefinitions = n.GetCollectionOfObjectValues<global::SalesPortal.Client.Models.AchievementDefinition>(global::SalesPortal.Client.Models.AchievementDefinition.CreateFromDiscriminatorValue)?.AsList(); } },
                { "commissionPayouts", n => { CommissionPayouts = n.GetCollectionOfObjectValues<global::SalesPortal.Client.Models.CommissionPoolPayout>(global::SalesPortal.Client.Models.CommissionPoolPayout.CreateFromDiscriminatorValue)?.AsList(); } },
                { "commissions", n => { Commissions = n.GetCollectionOfObjectValues<global::SalesPortal.Client.Models.Commission>(global::SalesPortal.Client.Models.Commission.CreateFromDiscriminatorValue)?.AsList(); } },
                { "compensationPlan", n => { CompensationPlan = n.GetObjectValue<global::SalesPortal.Client.Models.CompensationPlan>(global::SalesPortal.Client.Models.CompensationPlan.CreateFromDiscriminatorValue); } },
                { "compensationPlanId", n => { CompensationPlanId = n.GetLongValue(); } },
                { "id", n => { Id = n.GetLongValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "share", n => { Share = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::SalesPortal.Client.Models.AchievementDefinition>("achievementDefinitions", AchievementDefinitions);
            writer.WriteCollectionOfObjectValues<global::SalesPortal.Client.Models.CommissionPoolPayout>("commissionPayouts", CommissionPayouts);
            writer.WriteCollectionOfObjectValues<global::SalesPortal.Client.Models.Commission>("commissions", Commissions);
            writer.WriteObjectValue<global::SalesPortal.Client.Models.CompensationPlan>("compensationPlan", CompensationPlan);
            writer.WriteLongValue("compensationPlanId", CompensationPlanId);
            writer.WriteLongValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteDoubleValue("share", Share);
        }
    }
}
