// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace SalesPortal.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    #pragma warning disable CS1591
    public partial class ModelValidationResult : ApiException, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The firstError property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstError { get; private set; }
#nullable restore
#else
        public string FirstError { get; private set; }
#endif
        /// <summary>The firstErrorCode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstErrorCode { get; private set; }
#nullable restore
#else
        public string FirstErrorCode { get; private set; }
#endif
        /// <summary>The isValid property</summary>
        public bool? IsValid { get; private set; }
        /// <summary>The jsonError property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? JsonError { get; private set; }
#nullable restore
#else
        public string JsonError { get; private set; }
#endif
        /// <summary>The primary error message.</summary>
        public override string Message { get => base.Message; }
        /// <summary>The validationErrors property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::SalesPortal.Client.Models.ModelValidationError>? ValidationErrors { get; private set; }
#nullable restore
#else
        public List<global::SalesPortal.Client.Models.ModelValidationError> ValidationErrors { get; private set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SalesPortal.Client.Models.ModelValidationResult"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SalesPortal.Client.Models.ModelValidationResult CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::SalesPortal.Client.Models.ModelValidationResult();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "firstError", n => { FirstError = n.GetStringValue(); } },
                { "firstErrorCode", n => { FirstErrorCode = n.GetStringValue(); } },
                { "isValid", n => { IsValid = n.GetBoolValue(); } },
                { "jsonError", n => { JsonError = n.GetStringValue(); } },
                { "validationErrors", n => { ValidationErrors = n.GetCollectionOfObjectValues<global::SalesPortal.Client.Models.ModelValidationError>(global::SalesPortal.Client.Models.ModelValidationError.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
        }
    }
}
