// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SalesPortal.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    #pragma warning disable CS1591
    public partial class MonthlyReport : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The commission property</summary>
        public double? Commission { get; set; }
        /// <summary>The commissionPoolPayouts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::SalesPortal.Client.Models.CommissionPoolPayout>? CommissionPoolPayouts { get; set; }
#nullable restore
#else
        public List<global::SalesPortal.Client.Models.CommissionPoolPayout> CommissionPoolPayouts { get; set; }
#endif
        /// <summary>The commissions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::SalesPortal.Client.Models.Commission>? Commissions { get; set; }
#nullable restore
#else
        public List<global::SalesPortal.Client.Models.Commission> Commissions { get; set; }
#endif
        /// <summary>The date property</summary>
        public DateTimeOffset? Date { get; set; }
        /// <summary>The id property</summary>
        public long? Id { get; set; }
        /// <summary>The myTurnover property</summary>
        public double? MyTurnover { get; set; }
        /// <summary>The node property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SalesPortal.Client.Models.Node? Node { get; set; }
#nullable restore
#else
        public global::SalesPortal.Client.Models.Node Node { get; set; }
#endif
        /// <summary>The nodeId property</summary>
        public long? NodeId { get; set; }
        /// <summary>The teamTurnover property</summary>
        public double? TeamTurnover { get; set; }
        /// <summary>The totalTurnover property</summary>
        public double? TotalTurnover { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SalesPortal.Client.Models.MonthlyReport"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SalesPortal.Client.Models.MonthlyReport CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::SalesPortal.Client.Models.MonthlyReport();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "commission", n => { Commission = n.GetDoubleValue(); } },
                { "commissionPoolPayouts", n => { CommissionPoolPayouts = n.GetCollectionOfObjectValues<global::SalesPortal.Client.Models.CommissionPoolPayout>(global::SalesPortal.Client.Models.CommissionPoolPayout.CreateFromDiscriminatorValue)?.AsList(); } },
                { "commissions", n => { Commissions = n.GetCollectionOfObjectValues<global::SalesPortal.Client.Models.Commission>(global::SalesPortal.Client.Models.Commission.CreateFromDiscriminatorValue)?.AsList(); } },
                { "date", n => { Date = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetLongValue(); } },
                { "myTurnover", n => { MyTurnover = n.GetDoubleValue(); } },
                { "node", n => { Node = n.GetObjectValue<global::SalesPortal.Client.Models.Node>(global::SalesPortal.Client.Models.Node.CreateFromDiscriminatorValue); } },
                { "nodeId", n => { NodeId = n.GetLongValue(); } },
                { "teamTurnover", n => { TeamTurnover = n.GetDoubleValue(); } },
                { "totalTurnover", n => { TotalTurnover = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("commission", Commission);
            writer.WriteCollectionOfObjectValues<global::SalesPortal.Client.Models.CommissionPoolPayout>("commissionPoolPayouts", CommissionPoolPayouts);
            writer.WriteCollectionOfObjectValues<global::SalesPortal.Client.Models.Commission>("commissions", Commissions);
            writer.WriteDateTimeOffsetValue("date", Date);
            writer.WriteLongValue("id", Id);
            writer.WriteDoubleValue("myTurnover", MyTurnover);
            writer.WriteObjectValue<global::SalesPortal.Client.Models.Node>("node", Node);
            writer.WriteLongValue("nodeId", NodeId);
            writer.WriteDoubleValue("teamTurnover", TeamTurnover);
            writer.WriteDoubleValue("totalTurnover", TotalTurnover);
        }
    }
}
